services:
  - type: web
    name: flowboard
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -k geventwebsocket.gunicorn.workers.GeventWebSocketWorker -w 1 app:app